version: '3'
services:
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=search_engine_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql